import type { Lead, LeadDetail } from "@/lib/types";

const now = Date.now();

export const demoLeads: Lead[] = [
  {
    lead_id: "demo-lead-hot",
    name: "Aarav Mehta",
    phone_e164: "+91 98•••••210",
    property_interest: "3 BHK · The Canopy, Whitefield",
    budget_min: 12_000_000,
    budget_max: 16_000_000,
    city: "Bengaluru",
    locality: "Whitefield",
    source: "99acres",
    received_at: new Date(now - 1000 * 60 * 24).toISOString(),
    status: "engaged",
    call_run_id: "run_8f2c1a",
    call_status: "initiated",
    whatsapp_status: "accepted",
    whatsapp_accepted_at: new Date(now - 1000 * 60 * 23).toISOString(),
    time_to_call_initiation_ms: 1_840,
    intent_level: "hot",
    summary: "Aarav aur unki partner Whitefield mein 3 BHK dekh rahe hain. Budget ₹1.2–1.6 Cr hai, possession timeline clear hai, aur Saturday site visit ke liye ready hain.",
    next_followup_at: new Date(now + 1000 * 60 * 60 * 20).toISOString(),
    followup_count: 1,
    do_not_contact: false,
    call_consent: true,
    whatsapp_opt_in: true,
    preferred_followup_time: "Saturday, 11 AM",
    preferred_channel: "both",
    objections: ["Wants to compare maintenance costs"],
    interests: ["East-facing unit", "Near an international school"],
    budget_signal: "Within stated range",
    next_action: "book_site_visit",
    next_action_reason: "High intent and requested an in-person visit this weekend.",
  },
  {
    lead_id: "demo-lead-warm",
    name: "Priya Nair",
    phone_e164: "+91 97•••••604",
    property_interest: "2 BHK · Palm Grove Residences",
    budget_min: 7_000_000,
    budget_max: 9_000_000,
    city: "Pune",
    locality: "Baner",
    source: "Magicbricks",
    received_at: new Date(now - 1000 * 60 * 84).toISOString(),
    status: "dispatching",
    call_status: "queued",
    whatsapp_status: "accepted",
    time_to_call_initiation_ms: null,
    intent_level: "warm",
    summary: "Priya is exploring a 2 BHK in Baner before making a decision with her family. She asked for the floor plan on WhatsApp and prefers a weekday evening call.",
    next_followup_at: new Date(now + 1000 * 60 * 60 * 30).toISOString(),
    followup_count: 2,
    do_not_contact: false,
    call_consent: true,
    whatsapp_opt_in: true,
    preferred_followup_time: "Weekday evening",
    preferred_channel: "whatsapp",
    objections: ["Needs to discuss with family", "Comparing two locations"],
    interests: ["Floor plan", "Covered parking"],
    budget_signal: "Comfortable near upper end",
    next_action: "send_brochure",
    next_action_reason: "Send requested floor plan, then call after family review.",
  },
  {
    lead_id: "demo-lead-cold",
    name: "Kabir Shah",
    phone_e164: "+91 99•••••817",
    property_interest: "Villa plot · Aranya County",
    budget_min: 5_000_000,
    budget_max: 6_500_000,
    city: "Hyderabad",
    locality: "Shamshabad",
    source: "Website",
    received_at: new Date(now - 1000 * 60 * 60 * 4).toISOString(),
    status: "partial_failure",
    call_status: "failed",
    whatsapp_status: "suppressed",
    time_to_call_initiation_ms: null,
    intent_level: "cold",
    summary: "Kabir was gathering information and is not planning a visit yet. Call consent was not provided, so the voice channel was suppressed. WhatsApp is also suppressed until the lead opts in.",
    next_followup_at: new Date(now + 1000 * 60 * 60 * 48).toISOString(),
    followup_count: 0,
    do_not_contact: false,
    call_consent: false,
    whatsapp_opt_in: false,
    preferred_channel: "none",
    objections: ["Timeline is uncertain"],
    interests: ["Plot sizes", "Payment milestones"],
    budget_signal: "Early estimate",
    next_action: "nurture",
    next_action_reason: "Keep the enquiry warm; do not contact until consent is recorded.",
  },
];

export const demoDetails: Record<string, LeadDetail> = Object.fromEntries(
  demoLeads.map((lead) => [
    lead.lead_id,
    {
      lead,
      followups: lead.followup_count
        ? [{
            followup_id: `followup-${lead.lead_id}`,
            lead_id: lead.lead_id,
            run_id: lead.call_run_id,
            intent_level: lead.intent_level,
            next_action: lead.next_action,
            next_followup_at: lead.next_followup_at,
            channel: lead.preferred_channel,
            attempt_number: lead.followup_count,
            status: "pending",
            summary: lead.summary,
            objections: lead.objections,
            interests: lead.interests,
            budget_signal: lead.budget_signal,
            next_action_reason: lead.next_action_reason,
          }]
        : [],
      errors: lead.call_status === "failed"
        ? [{
            log_id: "error-demo-timeout",
            lead_id: lead.lead_id,
            api: "Dograh voice call",
            http_status: 504,
            error_message: "Provider did not confirm the call start. Check the provider execution before retrying.",
            attempt_count: 3,
            final: true,
            ambiguous: true,
            timestamp: lead.received_at,
            execution_id: "exec_demo_01",
          }]
        : [],
    },
  ]),
);
